import type { Metadata } from "next";
import "./globals.css";
import { inter, grotesk } from "./fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${inter.variable} ${grotesk.variable}`}
    >
      <body className="antialiased">{children}</body>
    </html>
  );
}

<form name="contact" data-netlify="true" hidden>
  <input type="hidden" name="form-name" value="contact" />
</form>


